[linters]
enable = [
    "gocyclo",
    "unconvert",
    "goimports",
    "unused",
    "vetshadow",
    "misspell",
    "nakedret",
    "errcheck",
#    "revive",  # had to disable it temporarily, workflow has older version that show error I don't have
    "ineffassign",
    "goconst",
    "vet",
    "unparam",
    "gofumpt",
    "gosimple",
    "govet",
    "staticcheck",    
]
